package fr.scabois.scabotheque.enums;

public enum PageType {
    LIST_ADHERENT, CREATE_ADHERENT, TABLES_BASE, LISTE_COURSES, AJOUT_COURSES, MODIF_COURSES, SUPPRESSION_COURSES,
    LIENS_UTILS, GESTION_FOURNISSEUR, GESTION_AGENCE, GESTION_METIER, GESTION_POLE, GESTION_SECTEUR, GESTION_VILLE
}
